# Generated by Django 2.0 on 2017-12-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, verbose_name='Contact name')),
                ('number', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Number')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of group')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='group',
            field=models.ManyToManyField(to='gci.Group'),
        ),
    ]
