# Generated by Django 2.0 on 2017-12-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gci', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='group',
        ),
    ]
