# Generated by Django 2.0 on 2017-12-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gci', '0002_remove_contact_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.TextField(max_length=255, verbose_name='List numbers'),
        ),
    ]
