# Generated by Django 2.0 on 2017-12-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gci', '0003_auto_20171209_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gruop',
            field=models.ManyToManyField(to='gci.Group'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name of group'),
        ),
    ]
