# Generated by Django 2.0 on 2017-12-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gci', '0004_auto_20171209_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='number',
            new_name='numbers',
        ),
    ]
