# Generated by Django 2.0 on 2017-12-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gci', '0005_auto_20171209_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='gruop',
            new_name='group',
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.TextField(max_length=255, verbose_name='Contact name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='numbers',
            field=models.TextField(max_length=255, verbose_name='Number'),
        ),
    ]
