# Generated by Django 2.0 on 2017-12-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gci', '0006_auto_20171209_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.TextField(max_length=255, verbose_name='Name of group'),
        ),
    ]
