# Generated by Django 2.0 on 2017-12-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gci', '0007_auto_20171209_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.TextField(max_length=100, verbose_name='Contact name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='numbers',
            field=models.TextField(max_length=400, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.TextField(max_length=100, verbose_name='Name of group'),
        ),
    ]
