# Generated by Django 2.0 on 2017-12-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gci', '0008_auto_20171209_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='contact',
            field=models.TextField(default=1, max_length=400, verbose_name='list of contacts'),
            preserve_default=False,
        ),
    ]
