# Generated by Django 2.0 on 2017-12-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gci', '0009_auto_20171209_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='cont',
            field=models.TextField(default=3, max_length=400, verbose_name='Contacs'),
            preserve_default=False,
        ),
    ]
