# Generated by Django 2.0 on 2017-12-09 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gci', '0010_group_cont'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='cont',
        ),
    ]
